package ie.soft8020.librarymanagement.domain;
 
import java.util.Collections;
import java.util.Date;
import java.util.List;
import java.util.stream.Collectors;

public class Child extends Member {
	private List<Loan> loans;
	private List<Book> books;
	private Double finesOutstanding;
	
	public Child(String name, Date dateOfBirth) {
		super();
		// When creating a member there can be situations when the list of 'books' 
		// or 'loans' are not be populated. We use an empty list in our constructor,
		// to prevent a NPE generated by toString() in this scenario.
		loans = Collections.<Loan>emptyList();
		books = Collections.<Book>emptyList();
	}
	
	@Override
	public List<Book> getBooks() {
		return books;
	}

	@Override
	public void setBooks(List<Book> books) {
		this.books = books;
	}
	
	@Override
	public List<Loan> getLoans() {
		return loans;
	}

	@Override
	public void setLoans(List<Loan> loan) {
		this.loans = loan;
	}
	
	@Override
	public Double getFinesOutstanding() {
		return finesOutstanding;
	}

	@Override
	public void setFinesOutstanding(Double finesOutstanding) {
		this.finesOutstanding = finesOutstanding;
	}

	@Override
	public String toString() {
		String out = "Child [memberID=" + getMemberID() + ", name=" + getName() + ", address=" + getAddress()
				+ ", dateOfBirth=" + getDateOfBirth() + ", loanLimit=" + getLoanLimit() + ", loanLength="
				+ getLoanLength() + ", finesOutstanding=" + getFinesOutstanding() + "\n"
				+ "books=[" + getListToString(getBooks()) + "]]\n"  
				+ "loan=[" + getListToString(getLoans()) + "]]";
		return out;
	}
	
	private String getListToString(List<?> list) {
		return list.stream().map(e -> e.toString()).collect(Collectors.joining(","));
	}
}
