package ie.soft8020.librarymanagement.domain;

import java.util.Collections;
import java.util.Date;
import java.util.List;

public class Member {
	
	private int memberID;
	private String name;
	private String address;
	private Date dateOfBirth;
	private int loanLimit;
	private int loanLength;
	private Double finesOutstanding;
	private List<Book> books; 
	
	
	public Member() {
		// When creating a member there can be situations when the list of 'books'
		// would not be populated. We use an empty list in our constructor, 
		// to prevent a NPE generated by toString() in this scenario. 
		books = Collections.<Book>emptyList();
	}
	
	public List<Book> getBooks() {
		return books;
	}
	
	public void setBooks(List<Book> books) {
		this.books = books;
	}
	
	public int getMemberID() {
		return memberID;
	}
	public void setMemberID(int memberID) {
		this.memberID = memberID;
	}
	public String getAddress() {
		return address;
	}
	public void setAddress(String address) {
		this.address = address;
	}
	public Date getDateOfBirth() {
		return dateOfBirth;
	}
	public void setDateOfBirth(Date dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}
	public int getLoanLimit() {
		return loanLimit;
	}
	public void setLoanLimit(int loanLimit) {
		this.loanLimit = loanLimit;
	}
	public int getLoanLength() {
		return loanLength;
	}
	public void setLoanLength(int loanLength) {
		this.loanLength = loanLength;
	}
	public Double getFinesOutstanding() {
		return finesOutstanding;
	}
	public void setFinesOutstanding(Double finesOutstanding) {
		this.finesOutstanding = finesOutstanding;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}

	@Override
	public String toString() {
		String out = "Member [memberID=" + memberID + ", name=" + name + ", address=" + address + ", dateOfBirth="
				+ dateOfBirth + ", loanLimit=" + loanLimit + ", loanLength=" + loanLength + ", finesOutstanding="
				+ finesOutstanding + "books=[";
		for (Book book : books) {
			out += book.toString();
		}
		out += "]]";
		return out;
	}	
}
