package ie.soft8020.librarymanagement.domain;

import java.util.Collections;
import java.util.Date;
import java.util.List;

public abstract class Member {

	private int memberID;
	private String name;
	private String address;
	private Date dateOfBirth;
	private List<Loan> loans;
	private List<Book> books;
	private double finesOutstanding;

	public Member(String name, Date dateOfBirth) {
		this.name = name;
		this.dateOfBirth = dateOfBirth;
		// When creating a member there can be situations when the List of 'books'
		// or 'loans' have not been populated. We use an empty list in our constructor,
		// to prevent a NPE, generated by toString() in this scenario.
		loans = Collections.emptyList();
		books = Collections.emptyList();
	}

	public abstract int getLoanLimit();

	public abstract void setLoanLimit(int loanLimit);

	public abstract int getLoanLength();

	public abstract void setLoanLength(int loanLength);

    public abstract void calculateFine(Member member);

	public int getMemberID() {
		return memberID;
	}

	public void setMemberID(int memberID) {
		this.memberID = memberID;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Date getDateOfBirth() {
		return dateOfBirth;
	}

	public void setDateOfBirth(Date dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public List<Book> getBooks() {
		return books;
	}

	public void setBooks(List<Book> books) {
		this.books = books;
	}

	public List<Loan> getLoans() {
		return loans;
	}

	public void setLoans(List<Loan> loans) {
		this.loans = loans;
	}

    public double getFinesOutstanding() {
        return finesOutstanding;
    }

    public void setFinesOutstanding(double finesOutstanding) {
        this.finesOutstanding = finesOutstanding;
    }
}
